name: Node.js CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install npm packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - id: variables
        name: Variables
        run: |
          echo "::set-output name=NPM_PACKAGE_NAME::$(npx -c 'echo $npm_package_name')"

      - name: Increment Build Count
        uses: dynatrace-oss/dynatrace-github-action@v7
        with:
          url: '${{ secrets.DT_ENV_URL }}'
          token: '${{ secrets.DT_API_TOKEN }}'
          metrics: |
            - metric: "github.buildcount"
              displayName: "GitHub Build Count"
              value: "1.0"
              dimensions:
                owner: "${{ github.repository_owner }}"
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                asset: "${{ steps.variables.outputs.NPM_PACKAGE_NAME }}"
