name: Node.js CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install npm packages
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build

      - id: variables
        name: Variables
        run: |
          echo "::set-output name=NPM_PACKAGE_NAME::$(npx -c 'echo $npm_package_name')"
